### ISSUE TITLE
DEFAULT_LOCAL_IP 读到多个 IP

### ISSUE THREAD

**Issue by puteulanus** [goodrain/rainbond-install#158]
环境是 Digitalocean 的 Centos 7.5 和 Ubuntu 16.04
init 之后卡在
```
[ERROR   ] Target 'manage01' did not return any data, probably due to an error.
manage01:
    Target 'manage01' did not return any data, probably due to an error.
 --- Waiting to start salt. ---
.timeout: failed to run command ‘salt’: No such file or directory
```

从这儿开始崩的
```
 --- Installing salt ... ---
 --- Salt-ssh test. ---
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 518, in handle_routine
    **target)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 920, in __init__
    self.shell = salt.client.ssh.shell.gen_shell(opts, **args)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/shell.py", line 63, in gen_shell
    shell = Shell(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/shell.py", line 90, in __init__
    self.host = host.strip('[]')
AttributeError: 'NoneType' object has no attribute 'strip'
```
应该是 `salt-ssh "*" --priv=/etc/salt/pki/master/ssh/salt-ssh.rsa test.ping -i` 的报错

`# ip addr show eth0`
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 9a:c9:7f:1a:e5:ca brd ff:ff:ff:ff:ff:ff
    inet 138.197.210.226/20 brd 138.197.223.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.46.0.5/16 brd 10.46.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::98c9:7fff:fe1a:e5ca/64 scope link
       valid_lft forever preferred_lft forever
```
`# ip addr show eth0 | awk '$1 == "inet" {gsub(/\/.*$/, "", $2); print $2}'`
```
138.197.210.226
10.46.0.5
```

 /tmp/LOCAL_IP
```
138.197.210.226 10.46.0.5
```

416 行 `Write_Sls_File master-private-ip $DEFAULT_LOCAL_IP` 的时候，`Write_Sls_File` 里 `slsfile=${3:-$MAIN_CONFIG}` 的 3 被 `10.46.0.5` 顶上没写进去

/srv/pillar/rainbond.sls
```
rbd-version: 3.7.2
rbd-path: /opt/rainbond
install-type: online
master-hostname: manage01
master-private-ip: null
master-public-ip: 138.197.210.226
vip: null
domain: 138.197.210.226
```

/etc/salt/roster 
```
manage01:
  host: null
```

salt-ssh 连不上 null 的 host 崩了

**Comment by ysicing** [comment]
@puteulanus  已经修复这个问题了
