### ISSUE TITLE
grctl conf get 报错 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by php-cpm** [goodrain/rainbond-install#168]
```
grctl conf get
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x16dbc49]

goroutine 1 [running]:
github.com/goodrain/rainbond/grctl/cmd.NewCmdConfigs.func2(0xc000836000, 0x0, 0xc000836000)
	/go/src/github.com/goodrain/rainbond/grctl/cmd/conf.go:77 +0x39
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.HandleAction(0x1811d80, 0x1b68a30, 0xc000836000, 0xc000824700, 0x0)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/app.go:502 +0xc8
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.Command.Run(0x1ad84db, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1af5766, 0x1a, 0x0, ...)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/command.go:210 +0x9aa
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc00036b500, 0xc0006a1ce0, 0x0, 0x0)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/app.go:383 +0x827
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.Command.startApp(0x1ad8db9, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1affbe3, 0x21, 0x0, ...)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/command.go:298 +0x808
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.Command.Run(0x1ad8db9, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1affbe3, 0x21, 0x0, ...)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/command.go:98 +0x1279
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.(*App).Run(0xc00036b340, 0xc00003a090, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/app.go:259 +0x6bb
github.com/goodrain/rainbond/cmd/grctl/server.Run(0x40f00d, 0x1a390e0)
	/go/src/github.com/goodrain/rainbond/cmd/grctl/server/grctl.go:46 +0x25d
main.main()
	/go/src/github.com/goodrain/rainbond/cmd/grctl/grctl.go:33 +0x5c
```

另外想问一下 初始化安装的时候没有设置 能否动态修改对外访问 IP eip。

**Comment by ysicing** [comment]
修改参考此文档 [调整已有域名解析](https://www.rainbond.com/docs/stable/operation-manual/trouble-shooting/domain-ops.html#part-3a9557cd9dab533c)

**Comment by php-cpm** [comment]
```
[root@manage01 ~]# grctl show
Manage your apps with webui：
10.9.xxx.xx:7070
The webui use websocket to provide more feture：
10.9.xxx.xx:6060
Your web apps use nginx for reverse proxy:
10.9.xxx.xx:80
```

我的使用环境中
A 机器安装了 goodrain ，但只有内网 ip。
B 机器有 nginx ，有外网ip。
因此无需调整域名解析，只需要在 B 机器的 nginx 配置反向代理即可。

```
  1 upstream backend-api {
  2     server 10.9.xx.xx:80;
  3 }
  4
  5 server {
  6     listen 80;
  7     server_name ~^(?<subdomain>.+)\.xxx.grapps\.cn$;
  8
  9     access_log off;
 10     error_log off;
 11
 12     location / {
 13         proxy_pass  http://backend-api;
 14         proxy_connect_timeout      60;
 15         proxy_send_timeout         60;
 16         proxy_read_timeout         60;
 17         proxy_set_header Host $http_host;
 18
 19         proxy_set_header x-forwarded-for  $remote_addr;
 20         proxy_buffer_size         64k;
 21         proxy_buffers             32 64k;
 22         charset utf-8;
 23     }
 24 }
```

设置前端反向代理 nginx 时要设置`proxy_set_header Host $http_host;` 不然会出现502，页面提示`您的应用正在准备中，请稍等一会儿`



对于管理面板可以如下设置
```
upstream backend-docker  {
    server 10.9.xxx.xx:7070;
}

server {
	listen 80;
	server_name docker.dev.xxxx.cn;

    access_log off;
    error_log off;

	location / {
        proxy_pass  http://backend-docker;
        proxy_connect_timeout      60;
        proxy_send_timeout         60;
        proxy_read_timeout         60;
	}
}
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
upstream backend-docker-ws {
    server 10.9.xxx.xx:6060;
}
server {
    listen 6060;
    server_name docker.dev.xxxxx.cn;
     access_log off;
     error_log off;

     location / {
         proxy_pass  http://backend-docker-ws;

         proxy_read_timeout 300s;
         proxy_send_timeout 300s;

         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $connection_upgrade;
     }
}
```
